/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppToast: typeof import('./components/AppToast.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    OuterNavbar: typeof import('./components/OuterNavbar.vue')['default']
    ProfileAvatar: typeof import('./components/profileAvatar.vue')['default']
    Registration: typeof import('./components/Registration.vue')['default']
    RegistrationForm: typeof import('./components/auth/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WorkInProgress: typeof import('./components/WorkInProgress.vue')['default']
  }
}
