/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/events': RouteRecordInfo<'/events', '/events', Record<never, never>, Record<never, never>>,
    '/historyView': RouteRecordInfo<'/historyView', '/historyView', Record<never, never>, Record<never, never>>,
    '/leadershipView': RouteRecordInfo<'/leadershipView', '/leadershipView', Record<never, never>, Record<never, never>>,
    '/ministries': RouteRecordInfo<'/ministries', '/ministries', Record<never, never>, Record<never, never>>,
    '/missionView': RouteRecordInfo<'/missionView', '/missionView', Record<never, never>, Record<never, never>>,
    '/ourBeliefs': RouteRecordInfo<'/ourBeliefs', '/ourBeliefs', Record<never, never>, Record<never, never>>,
    '/profileView': RouteRecordInfo<'/profileView', '/profileView', Record<never, never>, Record<never, never>>,
    '/services': RouteRecordInfo<'/services', '/services', Record<never, never>, Record<never, never>>,
  }
}
